global_defs {
    router_id garage
    enable_script_security
    script_user root
#    vrrp_startup_delay 5
#    vrrp_garp_master_delay 1
#    vrrp_garp_interval 1
    vrrp_version 3
    nftables
}
vrrp_instance VI_IPV4_LAN {
    state BACKUP
    interface br0
    virtual_router_id 56
    priority 100
    advert_int 1
    nopreempt
    unicast_peer {
        192.168.0.200
    }
    unicast_src_ip 192.168.0.151
    virtual_ipaddress {
        192.168.0.192/24
    }
    notify_master "/opt/vrrp_scripts/action.sh VI_IPV4_LAN Master"
    notify_backup "/opt/vrrp_scripts/action.sh VI_IPV4_LAN Backup"
    notify_fault  "/opt/vrrp_scripts/action.sh VI_IPV4_LAN Fault"
}
vrrp_instance VI_IPV4_VLAN2222 {
    state BACKUP
    interface br0.2222
    virtual_router_id 57
    priority 100
    advert_int 1
    nopreempt
    unicast_peer {
        172.222.0.200
    }
    unicast_src_ip 172.222.0.151
    virtual_ipaddress {
        172.222.0.1/16
    }
    notify_master "/opt/vrrp_scripts/action.sh VI_IPV4_VLAN2222 Master"
    notify_backup "/opt/vrrp_scripts/action.sh VI_IPV4_VLAN2222 Backup"
    notify_fault  "/opt/vrrp_scripts/action.sh VI_IPV4_VLAN2222 Fault"
}
vrrp_instance VI_IPV6_LAN {
    state BACKUP
    interface br0
    virtual_router_id 54
    priority 100
    advert_int 1
    nopreempt
    virtual_ipaddress {
        fe80::192/64
        fd00:192::1/64
    }
    notify_master "/opt/vrrp_scripts/action.sh VI_IPV6_LAN Master"
    notify_backup "/opt/vrrp_scripts/action.sh VI_IPV6_LAN Backup"
    notify_fault  "/opt/vrrp_scripts/action.sh VI_IPV6_LAN Fault"
}
vrrp_instance VI_IPV6_VLAN2222 {
    state BACKUP
    interface br0.2222
    virtual_router_id 55
    priority 100
    advert_int 1
    nopreempt
    virtual_ipaddress {
        fe80::2222/64
        fd00:2222::1/64 noprefixroute
    }
    notify_master "/opt/vrrp_scripts/action.sh VI_IPV6_VLAN2222 Master"
    notify_backup "/opt/vrrp_scripts/action.sh VI_IPV6_VLAN2222 Backup"
    notify_fault  "/opt/vrrp_scripts/action.sh VI_IPV6_VLAN2222 Fault"
}
