global_defs {
    router_id PodmanManager
    # Enable script security to enforce safe script execution
    enable_script_security
    # Define a non-root user to run scripts (e.g., 'keepalived_script' or 'nagios')
    script_user root
    vrrp_version 3
    nftables
}

vrrp_instance VI_IPV4_LAN {
    state MASTER
    interface br0
    virtual_router_id 56
    priority 200
    advert_int 1
    unicast_peer {
        192.168.0.151
    }
    unicast_src_ip 192.168.0.200
    virtual_ipaddress {
        192.168.0.192/24
    }
    notify_master "/opt/vrrp_scripts/action.sh VI_IPV4_LAN Master"
    notify_backup "/opt/vrrp_scripts/action.sh VI_IPV4_LAN Backup"
    notify_fault  "/opt/vrrp_scripts/action.sh VI_IPV4_LAN Fault"
}

vrrp_instance VI_IPV4_VLAN2222 {
    state MASTER
    interface br0.2222
    virtual_router_id 57
    priority 200
    advert_int 1
    unicast_peer {
        172.222.0.151
    }
    unicast_src_ip 172.222.0.200
    virtual_ipaddress {
        172.222.0.1/16
    }
    notify_master "/opt/vrrp_scripts/action.sh VI_IPV4_VLAN2222 Master"
    notify_backup "/opt/vrrp_scripts/action.sh VI_IPV4_VLAN2222 Backup"
    notify_fault  "/opt/vrrp_scripts/action.sh VI_IPV4_VLAN2222 Fault"
}

vrrp_instance VI_IPV6_LAN {
    state MASTER
    interface br0
    virtual_router_id 54
    priority 200
    advert_int 1
    virtual_ipaddress {
        fe80::192/64
        fd00:192::1/64
    }
    notify_master "/opt/vrrp_scripts/action.sh VI_IPV6_LAN Master"
    notify_backup "/opt/vrrp_scripts/action.sh VI_IPV6_LAN Backup"
    notify_fault  "/opt/vrrp_scripts/action.sh VI_IPV6_LAN Fault"
}

vrrp_instance VI_IPV6_VLAN2222 {
    state MASTER
    interface br0.2222
    virtual_router_id 55
    priority 200
    advert_int 1
    virtual_ipaddress {
        fe80::2222/64
        fd00:2222::1/64
    }
    notify_master "/opt/vrrp_scripts/action.sh VI_IPV6_VLAN2222 Master"
    notify_backup "/opt/vrrp_scripts/action.sh VI_IPV6_VLAN2222 Backup"
    notify_fault  "/opt/vrrp_scripts/action.sh VI_IPV6_VLAN2222 Fault"
}

