interface br0.2222 {
    AdvSendAdvert on;
    AdvManagedFlag off;
    AdvOtherConfigFlag off;

    AdvDefaultPreference high;

    prefix fd00:2222::/64 {
        AdvOnLink on;
        AdvAutonomous on;
        AdvRouterAddr on;
    };

    route ::/0 {
        AdvRoutePreference high;
        # RemoveRoute on;
    };

#    RDNSS fd00:2222::99 fd00:2222::28 {
#        AdvRDNSSLifetime 600;
#    };
};
